on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      - uses: chrisdickinson/setup-yq@latest
      -
        name: merge
        run: |
          cd /home/runner/work/yq-github-actiondemo/yq-github-actiondemo/
          yq m --append pod.yaml folder1/pod2.yaml
